### ISSUE TITLE
No options in Input sources

### ISSUE THREAD

**Issue by MartianInGreen** [lilyinstarlight/nixos-cosmic#254] opened 2024-08-10 06:59 UTC
Inside the settings app -> Input devices -> Keyboard -> Input Sources I can't select anything. Pretty sure this is somehow a Nix issue but I'm not sure where it's coming from
![image](https://github.com/user-attachments/assets/24d3888c-7045-4779-8de7-8b4796cc9288)
![image](https://github.com/user-attachments/assets/2cbc17d9-bb8e-4c89-abcb-968d9d5c306d)

**Comment by lilyinstarlight** [comment] 2024-08-10 17:03
Thanks for the report!

I've seen this issue, but I haven't gotten around to digging into it yet. If anyone digs into it before then, feel free to post what you find or post a PR :)

**Comment by Lemm1** [comment] 2024-08-12 11:33
After applying [this](https://github.com/lilyinstarlight/nixos-cosmic/issues/74#issuecomment-2197604718) workaround, I was able to add new input sources.

**Comment by MartianInGreen** [comment] 2024-08-13 12:28
Yep that works! Thanks. So it's an FHS issue as suspected.

**Comment by edgar-vincent** [comment] 2024-08-25 19:27
This issue is a duplicate of https://github.com/lilyinstarlight/nixos-cosmic/issues/74 and should probably be closed.

**Comment by Lemm1** [comment] 2024-08-31 11:06
Fixed with commit [4173750](https://github.com/lilyinstarlight/nixos-cosmic/commit/4173750608adf04be697d4c1434a202daf0ea35e) for me. Consider closing this issue.

**Comment by lilyinstarlight** [comment] 2024-09-25 21:13
Closing since this should be fixed. Feel free to reopen if you're still having issues after updating!

**Closed by lilyinstarlight** 2024-09-25 21:13 UTC
