### ISSUE TITLE
greeter: requires restarting cosmic-greeter-daemon to login

### ISSUE THREAD

**Issue by colemickens** [lilyinstarlight/nixos-cosmic#126] opened 2024-05-22 23:57 UTC
Hi,

These days, every time I start my Cosmic specialisation, I get a blank gray screen with a working cursor. This implies that cosmic-comp came up, but greeter failed to start up enough to even paint a (fallback) wallpaper.

If I switch to tty2, restart cosmic-greeter-daemon, switch back to tty1, the greeter loads and I can login.

I'm reporting this here, it may be one of these, or a combo. It seems others aren't easily reproing, maybe others will chime in with more thoughts/data:

1. We don't properly configure the greeter services to match upstream.
1. Something is wrong with how upstream prescribes running the greeter services.
1. There's simply a bug in greeter/greeter-daemon and I'm just getting unlucky?

Certainly feels like a race or mis-sequencing somewhere.

(I did spot check upstream, this module, etc. Nothing... seems wrong?)

**Comment by mbrea-c** [comment] 2024-06-09 10:59
I can reproduce this consistently on the latest kernel (6.9) but not on LTS (6.6). My laptop doesn't work well with the LTS kernel so I'm also trying to root cause this, so far no luck.

**Comment by colemickens** [comment] 2024-06-10 00:00
@mbrea-c Just for the sake of gathering info, etc, can you provide details about your setup. For example, are you also on a dual-AMD gpu system?

**Comment by mbrea-c** [comment] 2024-06-10 07:49
Sure! I'm also on dual-amd, specifically on a framework 16 with the following specs:

```
    System: Ryzen™ 9 7940HS
    Storage: WD_BLACK™ SN850X NVMe™- M.2 2280 - 2TB
    Memory: DDR5-5600 - 32GB (2 x 16GB)
    Expansion Bay Module: Graphics Module (AMD Radeon™ RX 7700S)
```
Other than that, I'm on the latest kernel (6.9.x) and running a Btrfs filesystem.

**Comment by RAVENz46** [comment] 2024-06-10 10:55
I have a similar but bit different issue.
After login, return this error log without cursor and gray screen.
It happens about 80%.
```console
2024-06-10T10:26:48.496437Z  INFO cosmic_session: Starting cosmic-session
2024-06-10T10:26:48.496933Z  INFO launch_pad: starting process ' COSMIC_SESSION_SOCK=12 cosmic-comp '
2024-06-10T10:26:49.159451Z ERROR launch_pad: process ' COSMIC_SESSION_SOCK=12 cosmic-comp ' failed with code 101 
2024-06-10T10:26:49.159495Z ERROR cosmic_session::comp: cosmic-comp exited with error code 101
2024-06-10T10:26:49.159518Z  INFO launch_pad: draining stdin receiver before restarting process
2024-06-10T10:26:49.159559Z  INFO launch_pad: sleeping for 6ms before restarting process cosmic-comp (restart 0)
2024-06-10T10:26:49.167155Z  INFO launch_pad: restarted process ' COSMIC_SESSION_SOCK=12 cosmic-comp ' , now at 1 restarts
2024-06-10T10:26:49.167215Z  INFO launch_pad: process 'ProcessKey(1v1)' cancelled
```
And rarely more wired issue happens that returning this error and screen blinking again and again.
But IDK why, this only happens on my desktop but not on my laptop.
Both of them have almost same config(latest kernel, bcachefs and so on).

Desktop
- intel 8700
- nvidia 1660Ti with 555 open(issue happens at least 550)

Laptop
- intel 155H

**Comment by mbrea-c** [comment] 2024-06-10 16:40
In my case this seems to be caused by `greetd.service` hitting its restart limit, this is the output of `systemctl status greetd.daemon`:

**Comment by lilyinstarlight** [comment] 2024-06-10 16:45
Can you grab a `journalctl -b0` with maybe more context on the failure?

**Comment by mbrea-c** [comment] 2024-06-10 16:58
Here it is:
```
Jun 10 17:54:27 nixframe systemd[1]: Started greetd.service.
Jun 10 17:54:27 nixframe greetd[1299]: pam_unix(greetd:session): session opened for user cosmic-greeter(uid=996) by (uid=0)
Jun 10 17:54:27 nixframe greetd[1299]: gkr-pam: gnome-keyring-daemon started properly
Jun 10 17:54:27 nixframe greetd[1299]: pam_unix(greetd:session): session closed for user cosmic-greeter
Jun 10 17:54:27 nixframe greetd[1296]: error: check_children: greeter exited without creating a session
Jun 10 17:54:27 nixframe systemd[1]: greetd.service: Deactivated successfully.
Jun 10 17:54:27 nixframe systemd[1]: greetd.service: Scheduled restart job, restart counter is at 1.
Jun 10 17:54:27 nixframe systemd[1]: Started greetd.service.
Jun 10 17:54:27 nixframe greetd[1379]: pam_unix(greetd:session): session opened for user cosmic-greeter(uid=996) by (uid=0)
Jun 10 17:54:27 nixframe greetd[1379]: gkr-pam: gnome-keyring-daemon started properly
Jun 10 17:54:27 nixframe greetd[1379]: pam_unix(greetd:session): session closed for user cosmic-greeter
Jun 10 17:54:27 nixframe greetd[1378]: error: check_children: greeter exited without creating a session
Jun 10 17:54:27 nixframe systemd[1]: greetd.service: Deactivated successfully.
Jun 10 17:54:28 nixframe systemd[1]: greetd.service: Scheduled restart job, restart counter is at 2.
Jun 10 17:54:28 nixframe systemd[1]: Started greetd.service.
Jun 10 17:54:28 nixframe greetd[1430]: pam_unix(greetd:session): session opened for user cosmic-greeter(uid=996) by (uid=0)
Jun 10 17:54:28 nixframe greetd[1430]: gkr-pam: gnome-keyring-daemon started properly
Jun 10 17:54:28 nixframe greetd[1430]: pam_unix(greetd:session): session closed for user cosmic-greeter
Jun 10 17:54:28 nixframe greetd[1429]: error: check_children: greeter exited without creating a session
Jun 10 17:54:28 nixframe systemd[1]: greetd.service: Deactivated successfully.
Jun 10 17:54:28 nixframe systemd[1]: greetd.service: Scheduled restart job, restart counter is at 3.
Jun 10 17:54:28 nixframe systemd[1]: Started greetd.service.
Jun 10 17:54:28 nixframe greetd[1484]: pam_unix(greetd:session): session opened for user cosmic-greeter(uid=996) by (uid=0)
Jun 10 17:54:28 nixframe greetd[1484]: gkr-pam: gnome-keyring-daemon started properly
Jun 10 17:54:28 nixframe greetd[1484]: pam_unix(greetd:session): session closed for user cosmic-greeter
Jun 10 17:54:28 nixframe greetd[1483]: error: check_children: greeter exited without creating a session
Jun 10 17:54:28 nixframe systemd[1]: greetd.service: Deactivated successfully.
Jun 10 17:54:29 nixframe systemd[1]: greetd.service: Scheduled restart job, restart counter is at 4.
Jun 10 17:54:29 nixframe systemd[1]: Started greetd.service.
Jun 10 17:54:29 nixframe greetd[1525]: pam_unix(greetd:session): session opened for user cosmic-greeter(uid=996) by (uid=0)
Jun 10 17:54:29 nixframe greetd[1525]: gkr-pam: gnome-keyring-daemon started properly
Jun 10 17:54:29 nixframe greetd[1525]: pam_unix(greetd:session): session closed for user cosmic-greeter
Jun 10 17:54:29 nixframe greetd[1524]: error: check_children: greeter exited without creating a session
Jun 10 17:54:29 nixframe systemd[1]: greetd.service: Deactivated successfully.
Jun 10 17:54:29 nixframe systemd[1]: greetd.service: Scheduled restart job, restart counter is at 5.
Jun 10 17:54:29 nixframe systemd[1]: greetd.service: Start request repeated too quickly.
Jun 10 17:54:29 nixframe systemd[1]: greetd.service: Failed with result 'start-limit-hit'.
Jun 10 17:54:29 nixframe systemd[1]: Failed to start greetd.service.
```

**Comment by mbrea-c** [comment] 2024-06-11 17:34
Small bit of additional info, I checked the logs again today and this time `gkr-pam` is throwing some error message:
```
Jun 11 18:21:20 nixframe systemd[1]: Started greetd.service.
Jun 11 18:21:20 nixframe greetd[1382]: pam_unix(greetd:session): session opened for user cosmic-greeter(uid=996) by (uid=0)
Jun 11 18:21:21 nixframe greetd[1382]: gkr-pam: gnome-keyring-daemon started properly
Jun 11 18:21:21 nixframe greetd[1382]: pam_unix(greetd:session): session closed for user cosmic-greeter
Jun 11 18:21:21 nixframe greetd[1381]: error: check_children: greeter exited without creating a session
Jun 11 18:21:21 nixframe systemd[1]: greetd.service: Deactivated successfully.
Jun 11 18:21:21 nixframe systemd[1]: greetd.service: Scheduled restart job, restart counter is at 1.
Jun 11 18:21:21 nixframe systemd[1]: Started greetd.service.
Jun 11 18:21:21 nixframe greetd[1433]: pam_unix(greetd:session): session opened for user cosmic-greeter(uid=996) by (uid=0)
Jun 11 18:21:21 nixframe greetd[1433]: gkr-pam: couldn't unlock the login keyring.
Jun 11 18:21:21 nixframe greetd[1433]: pam_unix(greetd:session): session closed for user cosmic-greeter
Jun 11 18:21:21 nixframe greetd[1432]: error: check_children: greeter exited without creating a session
Jun 11 18:21:21 nixframe systemd[1]: greetd.service: Deactivated successfully.
Jun 11 18:21:21 nixframe systemd[1]: greetd.service: Scheduled restart job, restart counter is at 2.
Jun 11 18:21:21 nixframe systemd[1]: Started greetd.service.
Jun 11 18:21:21 nixframe greetd[1475]: pam_unix(greetd:session): session opened for user cosmic-greeter(uid=996) by (uid=0)
Jun 11 18:21:21 nixframe greetd[1475]: gkr-pam: gnome-keyring-daemon started properly
Jun 11 18:21:22 nixframe greetd[1475]: pam_unix(greetd:session): session closed for user cosmic-greeter
Jun 11 18:21:22 nixframe greetd[1474]: error: check_children: greeter exited without creating a session
Jun 11 18:21:22 nixframe systemd[1]: greetd.service: Deactivated successfully.
Jun 11 18:21:22 nixframe systemd[1]: greetd.service: Scheduled restart job, restart counter is at 3.
Jun 11 18:21:22 nixframe systemd[1]: Started greetd.service.
Jun 11 18:21:22 nixframe greetd[1509]: pam_unix(greetd:session): session opened for user cosmic-greeter(uid=996) by (uid=0)
Jun 11 18:21:22 nixframe greetd[1509]: gkr-pam: couldn't unlock the login keyring.
Jun 11 18:21:22 nixframe greetd[1509]: pam_unix(greetd:session): session closed for user cosmic-greeter
Jun 11 18:21:22 nixframe greetd[1508]: error: check_children: greeter exited without creating a session
Jun 11 18:21:22 nixframe systemd[1]: greetd.service: Deactivated successfully.
Jun 11 18:21:22 nixframe systemd[1]: greetd.service: Scheduled restart job, restart counter is at 4.
Jun 11 18:21:22 nixframe systemd[1]: Started greetd.service.
Jun 11 18:21:22 nixframe greetd[1542]: pam_unix(greetd:session): session opened for user cosmic-greeter(uid=996) by (uid=0)
Jun 11 18:21:22 nixframe greetd[1542]: gkr-pam: gnome-keyring-daemon started properly
Jun 11 18:21:22 nixframe greetd[1542]: pam_unix(greetd:session): session closed for user cosmic-greeter
Jun 11 18:21:22 nixframe greetd[1541]: error: check_children: greeter exited without creating a session
Jun 11 18:21:22 nixframe systemd[1]: greetd.service: Deactivated successfully.
Jun 11 18:21:23 nixframe systemd[1]: greetd.service: Scheduled restart job, restart counter is at 5.
Jun 11 18:21:23 nixframe systemd[1]: greetd.service: Start request repeated too quickly.
Jun 11 18:21:23 nixframe systemd[1]: greetd.service: Failed with result 'start-limit-hit'.
Jun 11 18:21:23 nixframe systemd[1]: Failed to start greetd.service.
```

**Comment by addy419** [comment] 2024-06-11 22:50
Can you try adding
```
  environment.variables.XDG_RUNTIME_DIR = "/run/user/$UID";
  security.pam.services.gdm.enableGnomeKeyring = true;
```
and see if that fixes the problem?

**Comment by mbrea-c** [comment] 2024-06-12 21:15
> Can you try adding
> 
> ```
>   environment.variables.XDG_RUNTIME_DIR = "/run/user/$UID";
>   security.pam.services.cosmic-greeter.enableGnomeKeyring = true;
> ```
> 
> and see if that fixes the problem?

It doesn't unfortunately, same error as before.

> Edit: Switching back to 6.8 fixes my issues.

But this did fix it, and 6.8 is working perfectly on my machine so for now I'm calling this a win :)

Thanks!

**Comment by addy419** [comment] 2024-06-15 23:57
@mbrea-c 6.9.4 fixes these issues for me. Can you check it again?

**Comment by mbrea-c** [comment] 2024-06-16 12:24
@addy419 I can still reproduce it in 6.9.4,

**Comment by mbrea-c** [comment] 2024-06-16 12:34
@addy419 Yep, both AMD CPU and GPU
> ```
>     Laptop: Framework 16
>     System: Ryzen™ 9 7940HS
>     Storage: WD_BLACK™ SN850X NVMe™- M.2 2280 - 2TB
>     Memory: DDR5-5600 - 32GB (2 x 16GB)
>     Expansion Bay Module: Graphics Module (AMD Radeon™ RX 7700S)
> ```
Do you think it's related?

**Comment by addy419** [comment] 2024-06-20 19:27
@mbrea-c Yes, kernel 6.9 introduced the new p-state drivers for amd cpus and all my amd systems have been super unstable since 6.9. 6.9.4 is definitely more stable since I don't see the issue for now, but I can't say for sure yet.

I'm using 7600X.

**Comment by mikeslade** [comment] 2024-07-22 16:50
I have the same issue with the blank screen where cosmic greeter should display the login. I documented the error here: https://github.com/pop-os/cosmic-comp/issues/633. For me, it started a few weeks ago when they added the new KMS backend.

I am running the 6.8 kernel. AMD cpu. NVIDIA gpu.

**Comment by mikeslade** [comment] 2024-08-06 18:19
Everything is working for me now

**Comment by lilyinstarlight** [comment] 2024-09-25 21:44
Closing since people have reported it working now. Feel free to reopen if you are still experiencing this

**Closed by lilyinstarlight** 2024-09-25 21:44 UTC

**Comment by addy419** [comment] 2024-10-07 01:25
Hi all, I'm still experiencing this. Although, it only started again (as far as I remember) when I switched to stable from unstable. Does anyone use this flake with nixos stable?

**Comment by addy419** [comment] 2024-10-07 01:28
One thing I noticed is that it consistently happens when I just played a game on steam. If I do a hard restart and try to suspend, it works fine. Not sure what Steam has to do with it (or maybe my AMD GPU, D3cold is disabled can that be the cause?)
